version: '3'
services:
  exporter:
    image: prom/node-exporter
    command: --collector.textfile.directory=/textfiles
    volumes:
      #- ~/Library/Application Support/factorio/script-output/graftorio2/:/textfiles # macOS
      # - ${APPDATA}\Factorio\script-output\graftorio2:/textfiles # Windows
      - /home/${USER}/.factorio/script-output/graftorio2:/textfiles # Linux
    ports:
      - 9100:9100
  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./data/prometheus:/prometheus
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:5.1.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus_datasource.yml
      - ./data/prometheus_dashboard.yml:/etc/grafana/provisioning/dashboards/prometheus_dashboard.yml
      - ./data/grafana_dashboard.json:/var/lib/grafana/dashboards/grafana_dashboard.json
    ports:
      - 3000:3000
