{
 "title": "graftorio2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Satellites launched",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "factorio_items_launched_total{force=\"player\",name=\"satellite\"}"
    }
   ]
  },
  {
   "title": "Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "floor(factorio_tick / 25000)" }
   ]
  },
  {
   "title": "Oil Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"crude-oil\"}"
    },
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"heavy-oil\"}"
    },
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"light-oil\"} "
    },
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"petroleum-gas\"}"
    },
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"sulfuric-acid\"} "
    },
    {
     "expr": "factorio_fluid_production_output{force=\"player\",name=\"lubricant\"}"
    }
   ]
  },
  {
   "title": "Oil per 30s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(factorio_fluid_production_output{force=\"player\",name=\"crude-oil\"}[30s])"
    },
    {
     "expr": "increase(factorio_fluid_production_output{force=\"player\",name=\"heavy-oil\"}[30s])"
    },
    {
     "expr": "increase(factorio_fluid_production_output{force=\"player\",name=\"light-oil\"}[30s])"
    },
    {
     "expr": "increase(factorio_fluid_production_output{force=\"player\",name=\"petroleum-gas\"}[30s])"
    },
    {}
   ]
  },
  {
   "title": "Circuits per 30s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(factorio_item_production_output{force=\"player\",name=\"electronic-circuit\"}[30s]) "
    },
    {
     "expr": "increase(factorio_item_production_output{force=\"player\",name=\"advanced-circuit\"}[30s]) "
    },
    {
     "expr": "increase(factorio_item_production_output{force=\"player\",name=\"processing-unit\"}[30s]) "
    }
   ]
  },
  {
   "title": "Kill Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"behemoth-biter\"}",
     "legendFormat": "Behemoth Biter"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"small-spitter\"}",
     "legendFormat": "Small Spitter"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"medium-spitter\"}",
     "legendFormat": "Medium Spitter"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"big-spitter\"} ",
     "legendFormat": "Big Spitter"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"small-worm-turret\"}",
     "legendFormat": "Small Worm Turret"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"medium-worm-turret\"}",
     "legendFormat": "Medium Worm Turret"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"big-worm-turret\"}",
     "legendFormat": "Big Worm Turret"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"behemoth-worm-turret\"}",
     "legendFormat": "Behemoth Worm Turret"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"biter-spawner\"} ",
     "legendFormat": "Biter Spawner"
    },
    {
     "expr": "factorio_kill_count_input{force=\"player\",name=\"spitter-spawner\"}",
     "legendFormat": "Spitter Spawner"
    }
   ]
  }
 ]
}